static const char line_1d_vert[] = "#version 430 core\n"
                                   "\n"
                                   "uniform float center;// Point to be placed in the middle of the screen.\n"
                                   "uniform vec2 direction;// Direction in which the positive coordinate shoud be.\n"
                                   "uniform vec2 viewport;// Dimensions of the viewport.\n"
                                   "\n"
                                   "in float pos;\n"
                                   "in float t_in;\n"
                                   "in flat uint ei_in;\n"
                                   "\n"
                                   "out float t;\n"
                                   "out flat uint ei;\n"
                                   "out vec2 line_center;\n"
                                   "\n"
                                   "void main()\n"
                                   "{\n"
                                   "    gl_Position.xy = direction * (pos - center);\n"
                                   "    t = t_in;\n"
                                   "    cmap = cmap;\n"
                                   "    dof_offset = dof_offset_in;\n"
                                   "    order = order_in;\n"
                                   "    line_center = (gl_Position.xy + vec2(1, 1)) * viewport;\n"
                                   "    ei = ei_in;\n"
                                   "}\n";
