static const char line_1d_frag[] = "#version 430 core\n"
                                   "\n"
                                   "#define MAX_RECON_ORDER 8\n"
                                   "\n"
                                   "in float t;\n"
                                   "in flat uint ei;\n"
                                   "in vec2 line_center;\n"
                                   "\n"
                                   "uniform uint cmap_length;\n"
                                   "uniform float cmap_min;\n"
                                   "uniform float cmap_max;\n"
                                   "uniform uint cmap_is_log;\n"
                                   "uniform float line_width;\n"
                                   "\n"
                                   "struct element_info\n"
                                   "{\n"
                                   "    uint order;\n"
                                   "    uint dof_offset;\n"
                                   "};\n"
                                   "\n"
                                   "// Element info for all elements being rendered\n"
                                   "layout (std430, binding = 0) buffer element_buffer\n"
                                   "{\n"
                                   "    element_info elements[];\n"
                                   "};\n"
                                   "\n"
                                   "// Values of DoFs that are being rendered\n"
                                   "layout (std430, binding = 1) buffer coefficient_buffer\n"
                                   "{\n"
                                   "    float dof_values[];\n"
                                   "};\n"
                                   "\n"
                                   "// Colors in the colormap as unorm8\n"
                                   "layout (std430, binding = 2) buffer colormap_buffer\n"
                                   "{\n"
                                   "    uint color_vals[];\n"
                                   "};\n"
                                   "\n"
                                   "void main()\n"
                                   "{\n"
                                   "    float color_factor;\n"
                                   "    float center_distance = length(line_center - gl_FragCoord.xy);\n"
                                   "    if (center_distance > line_width)\n"
                                   "    {\n"
                                   "        discard;\n"
                                   "    }\n"
                                   "    color_factor = smoothstep(0, line_width, center_distance);\n"
                                   "\n"
                                   "    uint dof_offset = elements[ei].dof_offset;\n"
                                   "    uint order = elements[ei].order;\n"
                                   "    float value = basis_value * dof_values[dof_offset];\n"
                                   "    float basis_1 = 1.0;\n"
                                   "    float basis_2 = t;\n"
                                   "    for (uint i = 1; i < order; ++i)\n"
                                   "    {\n"
                                   "        value += basis_2 * dof_values[dof_offset + i];\n"
                                   "        float new_basis = float(2 * i + 1) * basis_2 - float(i) * basis_1;\n"
                                   "        basis_1 = basis_2;\n"
                                   "        basis_2 = new_basis;\n"
                                   "    }\n"
                                   "\n"
                                   "    float frac;\n"
                                   "\n"
                                   "    if (cmap_is_log == 1)\n"
                                   "    {\n"
                                   "        // Logarithmic colormap\n"
                                   "        frac = log2(value / cmap_min) / log2(cmap_max / cmap_min);\n"
                                   "    }\n"
                                   "    else\n"
                                   "    {\n"
                                   "        // Linear colormap\n"
                                   "        frac = (value - cmap_min) / (cmap_max - cmap_min);\n"
                                   "    }\n"
                                   "    frac = clamp(frac, 0.0, 0.99999);// Don't do up to 1\n"
                                   "\n"
                                   "    frac = frac * (cmap_length - 1);\n"
                                   "    color_index = uint(frac);\n"
                                   "    remainder = frac - float(color_index);\n"
                                   "\n"
                                   "    vec4 c_low  = unpackUnorm4x8(color_vals[ci.begin + color_index]);\n"
                                   "    vec4 c_high = unpackUnorm4x8(color_vals[ci.begin + color_index + 1]);\n"
                                   "\n"
                                   "    gl_FragColor = mix(c_low, c_high, remainder);\n"
                                   "    gl_FragColor.a *= color_factor;\n"
                                   "}\n"
                                   "\n";
