name: documentation

on: workflow_dispatch

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: pip
      - uses: awalsh128/cache-apt-pkgs-action@v1.5.0
        with:
          packages: libosmesa6-dev libgl1-mesa-dev
          version: 3.0      
      - uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: true
      - name: Install the extension
        run: uv sync --group docs
      - name: Build the docs
        run: uv run sphinx-build doc _build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
